ALTER TABLE user_services ADD COLUMN hostname TEXT NOT NULL DEFAULT '';
ALTER TABLE user_services ADD COLUMN ip TEXT NOT NULL DEFAULT '';
ALTER TABLE user_services ADD COLUMN ptr TEXT NOT NULL DEFAULT '';
ALTER TABLE user_services ADD COLUMN panel_url TEXT NOT NULL DEFAULT '';
ALTER TABLE user_services ADD COLUMN activated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP);
